### ISSUE TITLE
PlayerConfig parse themeColor exception SambaApi.java

### ISSUE THREAD

**Issue by rafamatias** [sambatech/player_sdk_android#1]
Hi,

There is a problem about parse theme color: Line 304 [https://github.com/sambatech/player_sdk_android/blob/master/sambaplayersdk/src/main/java/com/sambatech/player/SambaApi.java
](https://github.com/sambatech/player_sdk_android/blob/master/sambaplayersdk/src/main/java/com/sambatech/player/SambaApi.java)

**Android version**
Marshmallow

**Device**
Moto X

Thank you

**Comment by rafamatias** [comment]
The Sambatech's API returns the value of theme color as "###992233", the SDK replaces it by "##FF992233" and tries to convert into Long, then this causes an exception.

**Current**
playerConfig.getString("theme").replaceAll("^#?", ""), 16);

**Suggestion**
playerConfig.getString("theme").replaceAll("^#*", ""), 16);

**Comment by lzanol** [comment]
Hi @rafamatias, thanks for reporting and fixing, that's exactly it.

Could you please open a PR?

**Comment by lzanol** [comment]
@rafamatias The fix is already published on the maven repo, but I'll wait for your PR to update the sources. ;)

So you can update the dep: **com.sambatech.player:sdk-android:1.0.1-alpha**

**Comment by DeTakaki** [comment]
Hello,I'm trying to download the new version,but got no success. This is my error message:

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK third_party/java_src/error_prone/project/annotations/Annotations.gwt.xml
  	File1: /Users/detakaki/.gradle/caches/modules-2/files-2.1/com.sambatech.player.3rd/ima-android-sdk/3.1.3/6fb8cf3c5ef7a5abe0d82256220de6d48d182533/ima-android-sdk-3.1.3.jar
  	File2: /Users/detakaki/Documents/projects/android/me-salva-android/app/build/intermediates/exploded-aar/com.sambatech.player/sdk-android/1.0.1-alpha/jars/classes.jar
  	Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
```
Is there anything I'm doing wrong?

**Comment by rafamatias** [comment]
Hi @DeTakaki, I had the same problem. 

I don't know why, but the SDK import "ima-android-sdk" is duplicated. You can solve this excluding "ima-android-sdk" on app build gradle.

Try to add this code below:

compile ('com.sambatech.player:sdk-android:1.0.1-alpha'){
   exclude module: 'ima-android-sdk'
}

It works for me.

Thank's
