### ISSUE TITLE
ExoPlayer v2

### ISSUE THREAD

**Issue by lzanol** [sambatech/player_sdk_android#6]
### Tasks
- [ ] API
- [ ] Tratamento de erros
- [ ] Eventos/Interfaces
- [ ] DRM (Widevine CENC)
- [ ] Testes

**Comment by lzanol** [comment]
### Refs
- [Update ExoPlayer v2/GMF](https://github.com/googleads/google-media-framework-android/issues/129)

**Comment by luiz-byrro** [comment]
# Implementação do Google ExoPlayer 2

A nova versão do exoplayer traz uma estrutura com várias bibliotecas implementadas, cada biblioteca tem uma funcionalidade específica, como por exemplo UI, HLS, DASH e IMA. Assim é possível utilizar apenas o que for necessário para o desenvolvimento do novo sdk android.


 Ao atualizar o exoplayer, o GMF se torna obsoleto, pois a nova versão contém todos componentes necessários, além disso a google não tem atualizado o GMF [[1]](https://github.com/googleads/google-media-framework-android/issues/129).

 Foi feita uma análise para atualizar o exoplayer e remover o GMF do SDK:

### 1. Layout

Bastante alterado e simplificado, alguns componentes foram removidos e outros botões foram adicionados como o avançar e retroceder, além de próxima mídia e anterior.

![image](https://user-images.githubusercontent.com/18405622/32955075-0ad7d8b2-cb9c-11e7-9722-a34bd90cb214.png)

É relativamente fácil alterar o layout para adequar ao que temos hoje, é possível adicionar uma topbar com os componentes de menu, casting e live. Podemos aproveitar a implementação desses botões e dos menus. Também é possível fazer outras melhorias de layout e incluir o botão de fullscreen.

![captura de tela 2017-11-16 as 14 10 58](https://user-images.githubusercontent.com/18405622/32954633-d0c04a20-cb9a-11e7-85ac-94e4980a77bc.png)

### 2. IMA

Implementada agora no exoplayer como um módulo extension-ima, a utilização no sdk de acordo com esse tutorial é bastante simples [[2]](https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea) [[3]](https://github.com/google/ExoPlayer/blob/cdfe578/extensions/ima/README.md).

### 3. Cast

O novo exoplayer contém um módulo para integração com o chrome cast, não é possível encontrar muita documentação a respeito, pois foi adicionada recentemente ao exoplayer (está no branch dev-v2). [[4]](https://github.com/google/ExoPlayer/issues/2283)

### 4. Outputs e legendas

O método para trocar outputs é basicamente o mesmo [[5]](https://medium.com/google-exoplayer/exoplayer-2-x-track-selection-2b62ff712cc9). Também é possível selecionar várias saídas de áudio e legenda.

A camada de de legenda também é bastante parecida, só que a camada de UI do player implementa uma view para exibir legendas.


## Conclusão

É possível utilizar o ExoPlayer v2 de forma mais pura possível no SDK, mas são necessários vários ajustes, o principal é implementar todos os componentes de UI que não existem no exoplayer, são eles: tratamentos de erro, botão fullscreen, e topbar com o menu e outros botões. As mudanças podem ser implementadas sem alterar o código do exoplayer basta criar extensões das classes do library-ui (PlaybackControlView e SimpleExoPlayerView) com essas funcionalidades.
